
services:
 auth:
  build:
    context: .
    dockerfile: ./auth/Dockerfile
  image: micro-auth
  env_file:
    - ./auth/.env
  ports:
    - 8080:8080


 gateway:
  build:
    context: .
    dockerfile: ./gateway/Dockerfile
  image: micro-gateway

 product:
  build:
    context: .
    dockerfile: ./product/Dockerfile
  image: micro-product
  env_file:
    - ./product/.env
  ports:
    - 8081:8081

 cart:
  build:
    context: .
    dockerfile: ./cart/Dockerfile
  image: micro-cart
  env_file:
    - ./cart/.env
  ports:
    - 8082:8082


